server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
ribbon:
  #建立连接后读取资源所用时间
  ReadTimeout: 5000
  #建立连接所用时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监视哪个接口
    com.foxconn.springcloud.service.PaymentFeignServer: debug
